"""TGAT1 · ทักษะการพูด · การถาม-ตอบ (7 หัวข้อ)

ทุกข้อแต่งขึ้นใหม่ ไม่ได้มาจากข้อสอบจริง
format mcq4 (TGAT1 เป็นปรนัย 4 ตัวเลือก)
"""
from author import *

B = "tgat1.speaking.question_response."
FOUND = ["tgat1.speaking.foundation.function_bank"]


def d(*lines):
    """จัดบทสนทนาเป็น markdown: d("A: ...", "B: ______")"""
    out = []
    for ln in lines:
        who, _, text = ln.partition(": ")
        out.append(f"**{who}:** {text}")
    return "  \n".join(out)


def N(stem, ans, wrong, clue, explain, diff, tags=None):
    """โจทย์เพิ่มรอบ 3: บังคับให้มีวิธีคิดสองขั้นและคำใบ้สามระดับ"""
    return q(stem, ans, wrong,
             [("ระบุหน้าที่ของประโยค", clue),
              ("ตรวจคำตอบกับบริบทและระดับภาษา", "คำตอบต้องทำหน้าที่ต่อบทสนทนา ไม่ใช่แค่มีคำซ้ำ")],
             ["ดูว่าผู้พูดกำลังถาม ขอ เชิญ หรือแสดงความรู้สึก",
              "ตัดตัวเลือกที่ไวยากรณ์ได้แต่ตอบคนละหน้าที่",
              "เลือกคำตอบที่ทำให้บทสนทนาดำเนินต่ออย่างเป็นธรรมชาติ"],
             explain, diff=diff, sec=45 if diff == 3 else 55,
             reading="medium" if diff == 3 else "high", tags=tags)


# ============================================================ greeting_intro
tid = B + "greeting_intro"
L = lesson(tid, "ทักทาย แนะนำตัว และกล่าวลา",
    "รู้ว่าประโยคทักทายแต่ละแบบ 'ถาม' อะไรจริง ๆ และคำตอบแบบไหนเข้ากับระดับความเป็นทางการ",
    objectives=["ตอบคำทักทายที่ไม่ได้ถามจริง เช่น How's it going? ได้อย่างเป็นธรรมชาติ",
                "แยกคำทักทายตอนพบครั้งแรกกับคำทักทายคนที่รู้จักแล้ว",
                "เลือกคำกล่าวลาให้เข้ากับสถานการณ์"],
    prereq=FOUND, nxt=[B + "request_offer_permission"],
    blocks=[
        hook("ข้อสอบพาร์ทการพูดชอบให้เลือกคำตอบของประโยคสั้น ๆ อย่าง **\"How do you do?\"** "
             "ซึ่งคนจำนวนมากตอบผิดเพราะแปลตรงตัวว่า \"คุณทำอย่างไร\"\n\n"
             "หัวใจของหัวข้อนี้คือ **ดูหน้าที่ของประโยค ไม่ใช่แปลทีละคำ**"),
        concept("คำทักทายและคำตอบที่เข้าคู่กัน",
                "| ประโยค | ใช้เมื่อ | ตอบว่า |\n|---|---|---|\n"
                "| How do you do? | พบกันครั้งแรก ทางการ | How do you do? / Nice to meet you. |\n"
                "| Nice to meet you. | พบกันครั้งแรก | Nice to meet you, too. |\n"
                "| How's it going? / How are you doing? | คนรู้จัก ไม่ทางการ | Pretty good, thanks. And you? |\n"
                "| What's up? | เพื่อนสนิท | Not much. / Nothing much. |\n"
                "| Long time no see! | ไม่ได้เจอกันนาน | Yeah, it's been ages! |\n"
                "| Have a nice day. / Take care. | กล่าวลา | Thanks, you too. |"),
        concept("คำทักทายส่วนใหญ่ไม่ได้ถามจริง",
                "\"How's it going?\" ไม่ได้ต้องการให้เล่าชีวิตทั้งหมด คำตอบสั้น ๆ แล้ว **ถามกลับ** คือคำตอบที่เป็นธรรมชาติที่สุด\n\n"
                "\"What's up?\" ไม่ได้ถามว่า **อะไรอยู่ข้างบน** คำตอบ \"The sky.\" เป็นมุกตลก ไม่ใช่คำตอบในข้อสอบ"),
        technique("ถามว่าประโยคนี้ 'ทำหน้าที่' อะไร",
                  "ทุกข้อในพาร์ทถาม-ตอบ",
                  "อย่าแปลทีละคำแล้วเลือกตัวเลือกที่มีคำซ้ำกับคำถาม",
                  "ก่อนดูตัวเลือก ให้ระบุว่าประโยคแรกคือ ทักทาย / ขอบคุณ / ขอโทษ / ชวน / ขออนุญาต / ถามข้อมูล "
                  "แล้วหาคำตอบที่ทำหน้าที่ตอบรับหน้าที่นั้น ตัวลวงมักเป็นตัวเลือกที่ **มีคำเดียวกับคำถาม** แต่ทำหน้าที่ผิด",
                  tip="ดูหน้าที่ ไม่ใช่คำที่ซ้ำ"),
        example("ตัวอย่างที่ 1",
                d("A: Hi, I'm Ploy. I'm the new student in this class.", "B: ______"),
                [("หน้าที่ของประโยค: แนะนำตัวครั้งแรก", "คำตอบที่เหมาะคือทักทายกลับและแนะนำตัว"),
                 ("ตัดตัวที่มีคำซ้ำแต่ผิดหน้าที่ เช่น \"Yes, this is the new class.\"", "มีคำว่า new class แต่ไม่ได้ตอบการแนะนำตัว")],
                "\"Nice to meet you, Ploy. I'm Tony.\""),
        pitfall("แปล How do you do? ตรงตัว",
                "ตอบ \"How do you do?\" ด้วย \"I do my homework every day.\"",
                "How do you do? เป็นคำทักทายทางการตอนพบครั้งแรก ไม่ได้ถามว่าทำอะไร",
                "ตอบ \"How do you do?\" หรือ \"Nice to meet you.\"",
                "literal_translation"),
        pitfall("เลือกเพราะมีคำซ้ำกับคำถาม",
                "A: Take care! → เลือก \"I take care of my sister.\"",
                "Take care ในที่นี้เป็นคำกล่าวลา ไม่ได้พูดเรื่องดูแลใคร",
                "\"Thanks, you too.\" หรือ \"See you.\"",
                "word_match_trap"),
        summary("ดูหน้าที่ของประโยคก่อนดูตัวเลือก",
                "How do you do? และ Nice to meet you ใช้ตอนพบครั้งแรก",
                "How's it going? / What's up? ตอบสั้น ๆ แล้วถามกลับได้",
                "ตัวลวงมักมีคำซ้ำกับคำถามแต่ทำหน้าที่ผิด"),
        check(d("A: Long time no see! How have you been?", "B: ______"),
              ["I have been to Chiang Mai.", "Great, thanks! It's been ages, hasn't it?", "No, I can see you.", "Since last year."], 1,
              "A ทักทายคนที่ไม่ได้เจอกันนาน คำตอบที่เหมาะคือบอกว่าสบายดีและรับว่าไม่ได้เจอกันนานจริง ตัวเลือกอื่นมีคำซ้ำแต่ทำหน้าที่ผิด"),
        check(d("A: It was great talking to you. I have to go now.", "B: ______"),
              ["Me too. See you around!", "Where are you going to talk?", "I'm going now, too early.", "Yes, you talk very well."], 0,
              "A กำลังกล่าวลา คำตอบที่เหมาะคือกล่าวลากลับ"),
    ],
    patterns=["ให้ประโยคทักทาย แล้วเลือกคำตอบที่เหมาะสม",
              "ใช้ตัวลวงที่มีคำซ้ำกับคำถามแต่ทำหน้าที่ผิด",
              "แยกคำทักทายตอนพบครั้งแรกกับคำทักทายคนที่รู้จักแล้ว"],
    sources=["ผังการสอบ TGAT1 จาก mytcas.com (พาร์ทการพูด ส่วนการถาม-ตอบ)", "ประโยคและบทสนทนาแต่งขึ้นใหม่เพื่อการฝึก"],
)
P = [
    q(d("A: Hello, I'm Ms. Suda, your new English teacher.", "B: ______"),
      "Nice to meet you, Ms. Suda.",
      [("Yes, I'm your English.", "มีคำว่า English ซ้ำ แต่ไม่ได้ทักทายตอบ และประโยคไม่มีความหมาย"),
       ("I'm fine, thank you. And how are you today?", "เป็นคำตอบของ How are you? แต่ครูกำลังแนะนำตัว ไม่ได้ถามสารทุกข์"),
       ("Yes, our English teacher this year is new, too.", "ทวนคำว่า new teacher แต่ไม่ได้ตอบรับการแนะนำตัว")],
      [("ระบุหน้าที่: ครูแนะนำตัวครั้งแรก", "ต้องตอบด้วยคำทักทายตอนพบกันครั้งแรก"),
       ("เลือก Nice to meet you", "เป็นคำตอบมาตรฐานของการแนะนำตัว")],
      ["ครูกำลังทำอะไร ถามคำถาม หรือแนะนำตัว",
       "เมื่อมีคนแนะนำตัวครั้งแรก ภาษาอังกฤษนิยมตอบด้วยวลีอะไร",
       "ตัดตัวเลือกที่แค่ทวนคำในประโยคของครูออก"],
      "ตอบ Nice to meet you, Ms. Suda. เพราะครูกำลังแนะนำตัวครั้งแรก คำตอบที่เหมาะคือทักทายตอบรับการพบกัน",
      diff=1, sec=30, tags=["word_match_trap"]),
    q(d("A: Hey Mark! How's it going?", "B: ______"),
      "Not bad. How about you?",
      [("It's going to rain later, I think.", "มีคำว่า going ซ้ำ แต่เป็นการพยากรณ์อากาศ ไม่ใช่การตอบคำทักทาย"),
       ("I'm going to school by bus this morning.", "ตีความ going ว่าไปไหน ทั้งที่ How's it going? แปลว่าเป็นอย่างไรบ้าง"),
       ("Yes, it is.", "ตอบเหมือนคำถาม yes/no ทั้งที่คำถามนี้ขึ้นต้นด้วย How")],
      [("ระบุหน้าที่: ทักทายแบบไม่เป็นทางการ", "How's it going? = สบายดีไหม เป็นอย่างไรบ้าง"),
       ("ตอบสั้น ๆ แล้วถามกลับ", "Not bad. How about you? เป็นธรรมชาติที่สุด")],
      ["How's it going? ถามว่าไปไหน หรือถามว่าเป็นอย่างไรบ้าง",
       "คำถามขึ้นต้นด้วย How ตอบด้วย yes ได้ไหม",
       "คำตอบของคำทักทายมักสั้นและมีการถามกลับ"],
      "ตอบ Not bad. How about you? เพราะ How's it going? เป็นคำทักทายถามสารทุกข์ ไม่ได้ถามเรื่องการเดินทาง",
      diff=1, sec=30, tags=["literal_translation"]),
    q(d("A: How do you do? I'm David Lee from the marketing team.", "B: ______"),
      "How do you do? I'm Nida from finance.",
      [("I do my job very well.", "แปล How do you do? ตรงตัวว่าทำอย่างไร ทั้งที่เป็นคำทักทายทางการ"),
       ("I'm doing my homework.", "ตอบเหมือนถูกถามว่ากำลังทำอะไรอยู่"),
       ("Fine, thanks. Where is the marketing team's office?", "ตอบ Fine ซึ่งเป็นคำตอบของ How are you? และเปลี่ยนเรื่องไปถามทาง")],
      [("ระบุหน้าที่: ทักทายทางการตอนพบครั้งแรก พร้อมแนะนำตัว", "How do you do? ไม่ได้ถามว่าทำอะไร"),
       ("ตอบด้วย How do you do? และแนะนำตัวกลับ", "เป็นรูปแบบการตอบที่ถูกต้องในบริบททางการ")],
      ["How do you do? ใช้ในสถานการณ์แบบไหน",
       "ถ้ามีคนแนะนำตัวพร้อมชื่อแผนก เราควรตอบด้วยข้อมูลแบบเดียวกันไหม",
       "คำตอบมาตรฐานของ How do you do? คือทวนประโยคเดิม"],
      "ตอบ How do you do? I'm Nida from finance. เพราะเป็นการทักทายทางการตอนพบครั้งแรก ต้องทักทายตอบและแนะนำตัวกลับ",
      diff=2, sec=35, tags=["literal_translation"]),
    q(d("A: Well, it's getting late. I'd better get going.", "B: ______"),
      "OK. Take care!",
      [("Where are you getting?", "ตีความ get going ว่าจะไปเอาของ ทั้งที่แปลว่าต้องไปแล้ว"),
       ("Yes, it's late. I'm going to be late.", "ทวนคำว่า late แต่ไม่ได้กล่าวลาตอบ"),
       ("You'd better go to bed early.", "ใช้โครงสร้าง had better ซ้ำ แต่เป็นการสั่งสอนแทนการกล่าวลา")],
      [("ระบุหน้าที่: A กำลังบอกลา", "I'd better get going = ฉันควรไปได้แล้ว"),
       ("ตอบด้วยการกล่าวลา", "OK. Take care! ตอบรับและกล่าวลาได้ตรงสถานการณ์")],
      ["I'd better get going บอกว่า A กำลังจะทำอะไร",
       "เมื่ออีกฝ่ายบอกว่าต้องไปแล้ว เราควรตอบแบบไหน",
       "ระวังตัวเลือกที่ใช้คำหรือโครงสร้างซ้ำกับประโยคของ A"],
      "ตอบ OK. Take care! เพราะ A กำลังกล่าวลา คำตอบที่เหมาะจึงต้องตอบรับและกล่าวลากลับ",
      diff=2, sec=35, tags=["word_match_trap"]),
    q(d("A: Excuse me, are you Mr. Brown? I'm the student who emailed you about the scholarship.", "B: ______"),
      "Yes. You must be Ann. Have a seat.",
      [("Yes, I emailed the scholarship information to you last week.", "ทวนคำว่า emailed และ scholarship แต่สลับว่าใครส่งอีเมล"),
       ("No, I'm not a student.", "A ไม่ได้ถามว่า B เป็นนักเรียนไหม ตอบผิดประเด็น"),
       ("Excuse me, I don't have your email.", "ใช้ Excuse me ซ้ำ แต่ปฏิเสธโดยไม่ได้ยืนยันตัวตนตามที่ถูกถาม")],
      [("ระบุหน้าที่: A ถามยืนยันตัวตนและแนะนำตัวเอง", "B ต้องยืนยันว่าเป็นคุณบราวน์และตอบรับการแนะนำตัว"),
       ("ดูบริบท: B น่าจะรู้เรื่องอีเมลอยู่แล้ว", "You must be Ann. แสดงว่าจำได้ และเชิญนั่งเหมาะกับบริบทการนัดพบ")],
      ["A ถามคำถามอะไรก่อน",
       "คำถาม Are you Mr. Brown? ต้องตอบด้วยอะไร",
       "นอกจากยืนยันตัวตน B ควรตอบรับการแนะนำตัวของ A ไหม"],
      "ตอบ Yes. You must be Ann. Have a seat. เพราะยืนยันตัวตนตามคำถามและตอบรับการแนะนำตัวอย่างสุภาพ",
      diff=3, sec=45, reading="medium", tags=["word_match_trap"]),
    q(d("A: Hi, I don't think we've met. I'm Kevin, Jane's cousin.", "B: ______"),
      "Hi Kevin! I'm Tom, Jane's coworker.",
      [("I don't think so, too.", "ทวนประโยค I don't think แต่ไม่ได้แนะนำตัว และไวยากรณ์ผิด"),
       ("Yes, we've met many times.", "ขัดกับที่ A บอกว่าไม่เคยพบกัน"),
       ("Really? I didn't know Jane had any cousins at all. Is she your cousin or mine?", "ถามเรื่องญาติโดยไม่ได้ทักทายหรือแนะนำตัวตอบ")],
      [("ระบุหน้าที่: แนะนำตัวครั้งแรก พร้อมบอกความเกี่ยวข้องกับ Jane", "B ควรทักทาย แนะนำตัว และบอกความเกี่ยวข้องบ้าง"),
       ("คำตอบที่ดีต่อบทสนทนา", "บอกว่ารู้จัก Jane อย่างไร ทำให้คุยต่อได้")],
      ["A กำลังทำอะไร และบอกข้อมูลอะไรบ้าง",
       "การแนะนำตัวที่ดีมักบอกความเกี่ยวข้องกับคนที่รู้จักร่วมกัน",
       "ตัดตัวเลือกที่ขัดกับข้อมูลที่ A พูด"],
      "ตอบ Hi Kevin! I'm Tom, Jane's coworker. เพราะทักทาย แนะนำตัว และบอกความเกี่ยวข้องกับคนที่รู้จักร่วมกัน ทำให้บทสนทนาไปต่อได้",
      diff=2, sec=35),
]
P += [
 N(d("A: I don't think we've met. I'm Daniel from the design team.","B: ______"),"I'm Mali. It's a pleasure to meet you.",[("I'm meeting the design team tomorrow.","ทวนคำว่า meet แต่พูดถึงนัดหมาย"),("Yes, Daniel is on the design team.","พูดถึง Daniel แบบบุคคลที่สาม ไม่ตอบการแนะนำตัว"),("The pleasure was yesterday.","ตีความ pleasure เป็นเหตุการณ์และใช้กาลไม่เหมาะ")],"เป็นการแนะนำตัวเมื่อพบกันครั้งแรก","ตอบแนะนำตัวกลับและกล่าวยินดีที่ได้พบจึงเป็นธรรมชาติ",3,["word_match_trap"]),
 N(d("A: Well, I should let you get back to your guests.","B: ______"),"Thanks for coming. It was lovely catching up.",[("My guests got back an hour ago.","จับคำ get back ตามตัวอักษร"),("You should invite more guests next time.","เปลี่ยนเป็นวิจารณ์จำนวนแขก"),("No, I don't catch anything.","ตีความ catching ตามคำตรงตัว")],"ผู้พูดส่งสัญญาณจบบทสนทนาอย่างสุภาพ","คำตอบรับการลาและกล่าวขอบคุณสอดคล้องกับนัยของประโยค",5,["word_match_trap"]),
]
save(tid, "TGAT1", "mcq4", P, lesson=L)

# ============================================================ request_offer_permission
tid = B + "request_offer_permission"
L = lesson(tid, "ขอร้อง เสนอความช่วยเหลือ และขออนุญาต",
    "Would you mind...? ต้องตอบปฏิเสธถ้าจะยอม — เป็นกับดักที่ออกสอบบ่อยที่สุดในหัวข้อนี้",
    objectives=["แยกประโยคขอร้อง เสนอความช่วยเหลือ และขออนุญาตออกจากกันได้",
                "ตอบ Would you mind...? ได้ถูกทั้งกรณียอมและไม่ยอม",
                "ตอบรับหรือปฏิเสธอย่างสุภาพพร้อมเหตุผล"],
    prereq=FOUND, nxt=[B + "invitation"],
    blocks=[
        hook("\"Would you mind if I sat here?\" ถ้าอยากให้นั่ง ต้องตอบว่า **\"No, not at all.\"** ไม่ใช่ \"Yes\" "
             "เพราะคำถามถามว่า **รังเกียจไหม** การตอบ Yes แปลว่ารังเกียจ"),
        concept("3 หน้าที่ที่ต้องแยกให้ออก",
                "| หน้าที่ | ตัวอย่าง | ตอบรับ | ปฏิเสธสุภาพ |\n|---|---|---|---|\n"
                "| **ขอร้อง** | Could you help me...? / Can you...? | Sure. / Of course. | Sorry, I'm afraid I can't. + เหตุผล |\n"
                "| **เสนอช่วย** | Shall I...? / Would you like me to...? / Let me... | Yes, please. That's kind of you. | No, thanks. I can manage. |\n"
                "| **ขออนุญาต** | May I...? / Can I...? / Is it OK if I...? | Sure, go ahead. | I'm sorry, but... |"),
        concept("กับดัก Would you mind...?",
                "- **Would you mind + V-ing / if I...?** = รังเกียจไหม ถ้า...\n"
                "- ยอม → **No, not at all. / Of course not. / No, go ahead.**\n"
                "- ไม่ยอม → **Sorry, I'd rather you didn't.** / **I'm afraid...** + เหตุผล\n\n"
                "ตัวลวงยอดนิยมคือ \"Yes, of course.\" ซึ่งฟังดูสุภาพ แต่ความหมายคือ **ใช่ ฉันรังเกียจแน่นอน**"),
        technique("ถามว่า 'ใครจะเป็นคนทำ'",
                  "เมื่อแยกไม่ออกว่าเป็นการขอร้องหรือเสนอความช่วยเหลือ",
                  "ใช้กับประโยค Would you mind ไม่ได้ ต้องใช้กฎตอบปฏิเสธเมื่อยอมแทน",
                  "ถ้าผู้พูดจะทำเอง (Shall I carry it?) = เสนอช่วย ตอบ Yes, please / No, thanks · "
                  "ถ้าผู้พูดขอให้อีกฝ่ายทำ (Could you carry it?) = ขอร้อง ตอบ Sure / Sorry, I can't",
                  tip="Would you mind → ยอม = No"),
        example("ตัวอย่างที่ 1",
                d("A: Would you mind turning down the music? I'm trying to study.", "B: ______"),
                [("ระบุ: Would you mind + V-ing = ขอร้องแบบสุภาพมาก", "ถามว่ารังเกียจไหมที่จะลดเสียง"),
                 ("ถ้ายอม ต้องตอบปฏิเสธ", "Not at all. Sorry about that.")],
                "\"Not at all. Sorry about that.\""),
        pitfall("ตอบ Yes กับ Would you mind",
                "A: Would you mind if I borrowed your pen? → B: \"Yes, sure. Here you are.\"",
                "Yes แปลว่ารังเกียจ แต่ Here you are คือให้ยืม ข้อความขัดกันเอง",
                "\"No, not at all. Here you are.\"",
                "would_you_mind_yes"),
        pitfall("ตอบข้อเสนอด้วย Sure",
                "A: Shall I open the window for you? → B: \"Sure, I can.\"",
                "A จะเป็นคนเปิด ไม่ใช่ B คำว่า I can ผิดหน้าที่",
                "\"Yes, please. Thank you.\"",
                "offer_request_confusion"),
        summary("ขอร้อง: Could you...? → Sure / Sorry, I can't",
                "เสนอช่วย: Shall I...? → Yes, please / No, thanks",
                "ขออนุญาต: May I...? → Sure, go ahead",
                "Would you mind...? → ยอม = No, not at all"),
        check(d("A: Would you mind if I used your phone for a minute?", "B: ______"),
              ["Yes, I would. Here you are.", "No, not at all. Here you are.", "Yes, I mind your phone.", "No, I don't have a minute."], 1,
              "จะให้ยืม ต้องตอบปฏิเสธว่าไม่รังเกียจ No, not at all. ตัวเลือกแรกขัดกันเองระหว่าง Yes I would กับ Here you are"),
        check(d("A: Those boxes look heavy. Shall I give you a hand?", "B: ______"),
              ["Yes, I can give you.", "That's very kind of you. Thanks!", "No, my hand is fine.", "Sure, I'll help you."], 1,
              "A เสนอความช่วยเหลือ B ควรตอบรับและขอบคุณ ไม่ใช่เสนอช่วยกลับ"),
    ],
    patterns=["Would you mind...? ที่ต้องตอบปฏิเสธเมื่อยอม",
              "ประโยคเสนอความช่วยเหลือ Shall I...? ที่ต้องตอบ Yes, please",
              "ปฏิเสธสุภาพพร้อมเหตุผล"],
    sources=["ผังการสอบ TGAT1 จาก mytcas.com (พาร์ทการพูด ส่วนการถาม-ตอบ)", "ประโยคและบทสนทนาแต่งขึ้นใหม่เพื่อการฝึก"],
)
P = [
    q(d("A: Can I borrow your ruler for a moment?", "B: ______"),
      "Sure, go ahead.",
      [("Yes, I can borrow it.", "ตอบว่าตัวเองจะยืม ทั้งที่ A เป็นคนขอยืม"),
       ("No, it's a moment.", "ทวนคำว่า moment โดยไม่มีความหมาย"),
       ("Sure, lend me yours.", "ขอยืมกลับ สลับบทบาทผู้ยืม")],
      [("ระบุหน้าที่: A ขออนุญาตยืมของ", "ต้องตอบอนุญาตหรือปฏิเสธ"),
       ("Sure, go ahead. = เชิญเลย", "เป็นคำตอบอนุญาตที่เป็นธรรมชาติ")],
      ["A กำลังขออะไรจาก B",
       "ใครเป็นคนยืม ใครเป็นคนให้ยืม",
       "คำตอบอนุญาตแบบสั้น ๆ ที่ใช้บ่อยคืออะไร"],
      "ตอบ Sure, go ahead. เพราะ A ขออนุญาตยืมไม้บรรทัด คำตอบที่เหมาะคืออนุญาต",
      diff=1, sec=25, tags=["offer_request_confusion"]),
    q(d("A: Would you mind closing the door? It's a bit cold in here.", "B: ______"),
      "Not at all.",
      [("Yes, I would. I'll close it now.", "ตอบ Yes I would แปลว่ารังเกียจ แต่ต่อด้วยจะปิดให้ ข้อความขัดกัน"),
       ("Yes, it's cold.", "เห็นด้วยเรื่องอากาศแต่ไม่ได้ตอบคำขอร้อง"),
       ("No, I don't mind the cold.", "มีคำว่า mind แต่ตอบเรื่องความหนาว ไม่ได้ตอบว่าจะปิดประตูไหม")],
      [("ระบุ: Would you mind + V-ing = ขอร้องสุภาพ", "ถามว่ารังเกียจไหมที่จะปิดประตู"),
       ("ยอมทำ ต้องตอบปฏิเสธ", "Not at all. = ไม่รังเกียจเลย")],
      ["Would you mind closing... ถามว่าอะไร",
       "ถ้ายินดีปิดประตูให้ ต้องตอบว่ารังเกียจหรือไม่รังเกียจ",
       "ระวังตัวเลือกที่ขึ้นต้นด้วย Yes"],
      "ตอบ Not at all. เพราะ Would you mind ถามว่ารังเกียจไหม ถ้ายินดีทำให้ต้องตอบปฏิเสธว่าไม่รังเกียจ",
      diff=2, sec=30, tags=["would_you_mind_yes"]),
    q(d("A: You look lost. Would you like me to show you the way to the library?", "B: ______"),
      "Yes, please. That would be great.",
      [("Sure, I'll show you the way to the library right now.", "ตอบเหมือนตัวเองจะเป็นคนนำทาง สลับบทบาทกับ A"),
       ("No, I don't really like going to the library very much.", "ตีความ Would you like ว่าชอบไหม ทั้งที่เป็นการเสนอความช่วยเหลือ"),
       ("Not at all, it's far.", "ใช้คำตอบของ Would you mind ผิดที่")],
      [("ระบุ: Would you like me to...? = เสนอความช่วยเหลือ", "A จะเป็นคนนำทาง"),
       ("ตอบรับข้อเสนอ", "Yes, please. That would be great.")],
      ["ใครจะเป็นคนพาไปห้องสมุด A หรือ B",
       "Would you like me to... เป็นการขอร้องหรือเสนอช่วย",
       "คำตอบรับข้อเสนอความช่วยเหลือที่สุภาพคืออะไร"],
      "ตอบ Yes, please. That would be great. เพราะ A เสนอจะพาไปห้องสมุด B ควรตอบรับข้อเสนอ",
      diff=2, sec=30, tags=["offer_request_confusion"]),
    q(d("A: Could you cover my shift on Saturday? I have a family event.", "B: ______"),
      "Sorry, I can't. I'm away that day.",
      [("Yes, I have a big family event on Saturday, too.", "ทวนคำว่า family event แต่ไม่ได้ตอบว่าจะทำงานแทนไหม"),
       ("No, I won't cover it at all.", "ปฏิเสธห้วน ๆ ไม่สุภาพ และ at all ทำให้ฟังรุนแรง"),
       ("Sure, you can cover mine.", "สลับบทบาท เสนอให้ A ทำแทนตัวเองแทน")],
      [("ระบุ: A ขอร้องให้ทำงานแทน", "ต้องตอบรับหรือปฏิเสธคำขอ"),
       ("ปฏิเสธสุภาพ: ขอโทษ + บอกว่าทำไม่ได้ + เหตุผล", "เป็นรูปแบบที่ข้อสอบถือว่าเหมาะสมที่สุดเมื่อปฏิเสธ")],
      ["A ขออะไรจาก B",
       "ตัวเลือกไหนตอบคำขอโดยตรง",
       "การปฏิเสธที่สุภาพควรมีส่วนประกอบอะไรบ้าง"],
      "ตอบ Sorry, I can't. I'm away that day. เพราะเป็นการปฏิเสธคำขอร้องอย่างสุภาพพร้อมเหตุผล",
      diff=3, sec=40),
    q(d("A: Would you mind if I opened the window?", "B: ______"),
      "Actually, I'd rather you didn't. I have a cold.",
      [("Yes, please open it.", "Yes ในที่นี้แปลว่ารังเกียจ แต่ต่อด้วยให้เปิด ข้อความขัดกัน"),
       ("No, I would mind it.", "No แปลว่าไม่รังเกียจ แต่ต่อด้วย I would mind ขัดกันเอง"),
       ("Not at all. But I'd rather you didn't, because I have a cold.", "Not at all คือยอม แต่ I'd rather you didn't คือไม่ยอม ขัดกันเอง")],
      [("ระบุ: ขออนุญาตแบบ Would you mind if...", "ถามว่ารังเกียจไหม"),
       ("ตรวจความสอดคล้องของทุกตัวเลือก", "สามตัวเลือกขัดกันเองระหว่างคำตอบกับการกระทำ"),
       ("ปฏิเสธสุภาพ: I'd rather you didn't + เหตุผล", "เป็นคำตอบเดียวที่สอดคล้องตลอดประโยค")],
      ["Would you mind if I opened... ถามว่าอะไร",
       "ตรวจว่าแต่ละตัวเลือกความหมายช่วงแรกกับช่วงหลังไปทางเดียวกันไหม",
       "I'd rather you didn't แปลว่ายอมหรือไม่ยอม"],
      "ตอบ Actually, I'd rather you didn't. I have a cold. เพราะเป็นการปฏิเสธที่สุภาพและสอดคล้องกันทั้งประโยค ตัวเลือกอื่นขัดกันเอง",
      diff=4, sec=50, tags=["would_you_mind_yes"]),
    q(d("A: Let me carry that bag for you.", "B: ______"),
      "Thanks, but I can manage.",
      [("OK, let me carry it.", "ทวนประโยคของ A ทำให้ไม่รู้ว่าใครจะถือ"),
       ("Sorry, I can't carry your bag.", "ตีความเหมือน A ขอให้ช่วยถือกระเป๋าของ A"),
       ("Yes, you can't.", "ไวยากรณ์และความหมายขัดกัน")],
      [("ระบุ: Let me... = เสนอความช่วยเหลือ", "A จะถือกระเป๋าให้ B"),
       ("ปฏิเสธข้อเสนออย่างสุภาพ", "Thanks, but I can manage. = ขอบคุณ แต่ถือเองได้")],
      ["Let me... ใครจะเป็นคนทำ",
       "กระเป๋าเป็นของใคร",
       "การปฏิเสธข้อเสนอความช่วยเหลือแบบสุภาพพูดว่าอย่างไร"],
      "ตอบ Thanks, but I can manage. เพราะ A เสนอจะถือกระเป๋าให้ และนี่คือการปฏิเสธข้อเสนออย่างสุภาพ",
      diff=2, sec=30, tags=["offer_request_confusion"]),
]
P += [
 N(d("A: Could you keep an eye on my bag while I order?","B: ______"),"Of course. I'll watch it for you.",[("Yes, your bag has two eyes.","แปลสำนวน keep an eye on ตรงตัว"),("No, I couldn't order it.","สลับผู้ขอและสิ่งที่ขอ"),("The counter is over there.","บอกทางแต่ไม่ตอบคำขอเฝ้ากระเป๋า")],"เป็นคำขอให้ช่วยดูแลของชั่วคราว","ตอบรับและทวนสิ่งที่จะช่วยได้ตรงหน้าที่",3,["literal_translation"]),
 N(d("A: Would you mind if I moved your notes to this shelf?","B: ______"),"Not at all. I need the desk space too.",[("Yes, I would move them yesterday.","yes ทำให้ความหมายเป็นขัดข้องและกาลผิด"),("No, you wouldn't mind.","ตอบแทนความรู้สึกของผู้ถาม"),("The shelf has already moved.","สลับผู้กระทำและจับคำ move")],"Would you mind if I ... ถามว่าขัดข้องหรือไม่","Not at all แปลว่าไม่ขัดข้องและเหตุผลถัดมาสอดคล้องกัน",5,["would_you_mind_yes"]),
]
save(tid, "TGAT1", "mcq4", P, lesson=L)

# ============================================================ invitation
tid = B + "invitation"
L = lesson(tid, "ชวน ตอบรับ และปฏิเสธอย่างสุภาพ",
    "ตอบรับให้กระตือรือร้น ปฏิเสธให้มีขอบคุณ ขอโทษ เหตุผล และถ้าเป็นไปได้ เสนอทางอื่น",
    objectives=["จำรูปประโยคชวนที่ใช้บ่อย", "ตอบรับคำชวนอย่างเป็นธรรมชาติ", "ปฏิเสธคำชวนอย่างสุภาพครบองค์ประกอบ"],
    prereq=FOUND, nxt=[B + "apology_thanks"],
    blocks=[
        hook("การปฏิเสธคำชวนในภาษาอังกฤษมีสูตร ถ้าตอบแค่ \"No.\" จะฟังห้วนมาก "
             "ข้อสอบมักวางตัวเลือกปฏิเสธที่ **ถูกความหมาย แต่ไม่สุภาพ** ไว้เป็นตัวลวง"),
        concept("รูปประโยคชวน",
                "- **Would you like to** + V? — สุภาพ ทางการได้\n"
                "- **Do you want to** + V? — ทั่วไป\n"
                "- **How about / What about** + V-ing? — เสนอทางเลือก\n"
                "- **Why don't we** + V? / **Let's** + V. — ชวนทำด้วยกัน\n"
                "- **Are you free** + เวลา? — ถามก่อนชวน"),
        concept("แนวทางตอบ",
                "**ตอบรับ:** I'd love to! / That sounds great. / Sure, what time?\n\n"
                "**ปฏิเสธอย่างสุภาพ:** เลือกใช้ ขอบคุณ/แสดงว่าอยากไป → ขอโทษ → เหตุผล → เสนอทางอื่น ตามความเหมาะสม "
                "ไม่จำเป็นต้องมีครบทุกส่วนในคำตอบสั้น แต่ควรมีเหตุผลและไม่ห้วน\n"
                "> \"Thanks for asking! I'd love to, but I'm afraid I have to work that day. How about next weekend?\""),
        technique("ดูทั้งความหมายและน้ำเสียง",
                  "เมื่อมีตัวเลือกที่ความหมายถูกมากกว่าหนึ่งตัว",
                  "อย่าตัดตัวเลือกที่ยาวทิ้งเพราะคิดว่าเยิ่นเย้อ ในข้อนี้ความสุภาพมักต้องใช้คำเพิ่ม",
                  "ขั้นแรกตัดตัวที่ความหมายผิด (ตอบไม่ตรงคำชวน) ขั้นที่สองเลือกตัวที่ **สุภาพกว่า** ระหว่างตัวที่เหลือ",
                  tip="ปฏิเสธ = ขอบคุณ + ขอโทษ + เหตุผล (+ ทางอื่น)"),
        example("ตัวอย่างที่ 1",
                d("A: Would you like to join us for dinner on Friday?", "B: ______"),
                [("ระบุ: คำชวนแบบสุภาพ", "B ตอบรับหรือปฏิเสธก็ได้ แต่ต้องสุภาพ"),
                 ("ถ้าปฏิเสธ ใช้สูตร", "\"Thank you, I'd love to, but I already have plans on Friday.\"")],
                "\"Thank you, I'd love to, but I already have plans on Friday.\""),
        pitfall("ตอบรับด้วย Yes, I like.",
                "A: Would you like to come? → B: \"Yes, I like.\"",
                "Would you like เป็นคำชวน ไม่ได้ถามว่าชอบไหม และ like ต้องมีกรรม",
                "\"Yes, I'd love to.\"",
                "would_like_as_like"),
        summary("รูปชวน: Would you like to / Do you want to / How about V-ing / Why don't we / Let's",
                "ตอบรับ: I'd love to / That sounds great",
                "ปฏิเสธ: ขอบคุณ + ขอโทษ + เหตุผล + (ทางอื่น)",
                "ระวังตัวเลือกที่ความหมายถูกแต่ไม่สุภาพ"),
        check(d("A: How about going to the new café after class?", "B: ______"),
              ["Yes, I go.", "That sounds great! What time?", "About the café is new.", "No."], 1,
              "ตอบรับคำชวนอย่างกระตือรือร้นและถามรายละเอียด"),
    ],
    patterns=["ให้คำชวนแล้วเลือกคำตอบรับที่เป็นธรรมชาติ", "ให้เลือกคำปฏิเสธที่สุภาพที่สุด", "ตัวลวงเป็นคำปฏิเสธที่ห้วนเกินไป"],
    sources=["ผังการสอบ TGAT1 จาก mytcas.com (พาร์ทการพูด ส่วนการถาม-ตอบ)", "ประโยคและบทสนทนาแต่งขึ้นใหม่เพื่อการฝึก"],
)
P = [
    q(d("A: Do you want to play badminton this evening?", "B: ______"),
      "Sure! Where shall we meet?",
      [("Yes, I want badminton.", "ไวยากรณ์ผิดและไม่เป็นธรรมชาติ"),
       ("I played badminton yesterday evening.", "เล่าเรื่องเมื่อวานแต่ไม่ได้ตอบรับหรือปฏิเสธคำชวน"),
       ("No, I don't want this evening.", "ปฏิเสธห้วน ๆ และไวยากรณ์ผิด")],
      [("ระบุ: คำชวนแบบทั่วไป", "Do you want to...?"),
       ("ตอบรับและถามรายละเอียด", "Sure! Where shall we meet?")],
      ["A กำลังทำอะไร",
       "ตัวเลือกไหนตอบรับหรือปฏิเสธคำชวนจริง ๆ",
       "คำตอบรับที่ดีมักถามรายละเอียดต่อ เช่น เวลาหรือสถานที่"],
      "ตอบ Sure! Where shall we meet? เพราะตอบรับคำชวนและถามรายละเอียดต่ออย่างเป็นธรรมชาติ",
      diff=1, sec=25),
    q(d("A: We're having a small party for Nat's birthday on Saturday. Would you like to come?", "B: ______"),
      "Thanks for inviting me, but I'll be away that weekend.",
      [("No, I don't like parties.", "ปฏิเสธโดยบอกว่าไม่ชอบ ซึ่งไม่สุภาพกับคนที่ชวน"),
       ("Yes, I really like Nat's birthday parties every year.", "ตีความ Would you like ว่าชอบไหม"),
       ("I can't. Saturday.", "ปฏิเสธห้วนเกินไป ไม่มีขอบคุณหรือเหตุผลที่ชัด")],
      [("ระบุ: คำชวนไปงานวันเกิด", "ตอบรับหรือปฏิเสธก็ได้ แต่ต้องสุภาพ"),
       ("ตรวจตัวเลือกปฏิเสธ", "ตัวที่มีขอบคุณและเหตุผลสุภาพที่สุด")],
      ["Would you like to come? เป็นคำถามเรื่องความชอบหรือคำชวน",
       "ตัวเลือกปฏิเสธตัวไหนสุภาพที่สุด",
       "การปฏิเสธที่สุภาพควรมีคำขอบคุณและเหตุผล"],
      "ตอบ Thanks for inviting me, but I'll be away that weekend. เพราะปฏิเสธอย่างสุภาพด้วยคำขอบคุณและเหตุผล",
      diff=2, sec=35, tags=["would_like_as_like"]),
    q(d("A: Why don't we study together at the library tomorrow?", "B: ______"),
      "Good idea! Is 9 o'clock OK?",
      [("Because the library is closed.", "ตอบ Why ด้วย Because เหมือนถูกถามเหตุผล ทั้งที่ Why don't we เป็นคำชวน"),
       ("I don't know why.", "ตีความตามตัวอักษรว่าถามเหตุผล"),
       ("Yes, we don't.", "ไวยากรณ์และความหมายขัดกัน")],
      [("ระบุ: Why don't we + V? = ชวนทำด้วยกัน", "ไม่ได้ถามเหตุผล"),
       ("ตอบรับและเสนอเวลา", "Good idea! Is 9 o'clock OK?")],
      ["Why don't we... ถามเหตุผลจริงหรือเป็นการชวน",
       "ถ้าเป็นคำชวน ต้องตอบด้วย Because ไหม",
       "คำตอบรับที่ดีมักเสนอรายละเอียดต่อ"],
      "ตอบ Good idea! Is 9 o'clock OK? เพราะ Why don't we... เป็นคำชวน ไม่ได้ถามเหตุผล คำตอบที่เหมาะคือตอบรับพร้อมเสนอเวลา",
      diff=2, sec=30, tags=["literal_translation"]),
    q(d("A: Are you free on Sunday afternoon? There's a photography exhibition I think you'd enjoy.", "B: ______"),
      "Oh, I'd love to go, but I have a make-up class. Is it open next weekend?",
      [("Yes, I'm free. I don't enjoy it.", "บอกว่าว่าง แต่ไม่ชอบ ทำให้ไม่สุภาพและขัดกับการตอบรับ"),
       ("No, I'm not free on Sunday. Besides, photography exhibitions are boring.", "ปฏิเสธพร้อมวิจารณ์สิ่งที่อีกฝ่ายชอบ ไม่สุภาพ"),
       ("I enjoyed the exhibition on Sunday.", "พูดเหมือนไปมาแล้ว ไม่ได้ตอบคำชวน")],
      [("ระบุ: ถามว่าว่างไหม แล้วชวนไปงาน", "เป็นคำชวน"),
       ("ตัวเลือกที่ดีที่สุด: แสดงว่าอยากไป + เหตุผลที่ไปไม่ได้ + เสนอทางอื่น", "ครบสูตรปฏิเสธที่สุภาพ"),
       ("ตัดตัวที่ไม่สุภาพหรือไม่ตอบคำชวน", "เหลือตัวเดียวที่เหมาะ")],
      ["A ถามแค่ว่าว่างไหม หรือกำลังชวน",
       "ตัวเลือกไหนปฏิเสธโดยไม่ทำให้อีกฝ่ายเสียความรู้สึก",
       "การเสนอวันอื่นช่วยให้การปฏิเสธดีขึ้นอย่างไร"],
      "ตอบ Oh, I'd love to go, but I have a make-up class. Is it open next weekend? เพราะปฏิเสธอย่างสุภาพครบทั้งแสดงความสนใจ เหตุผล และเสนอทางอื่น",
      diff=3, sec=45, reading="medium"),
    q(d("A: Let's grab some lunch.", "B: ______"),
      "Sounds good. I'm starving!",
      [("Yes, let's not.", "ความหมายขัดกัน"),
       ("I grab my lunch.", "ทวนคำว่า grab แต่ไม่ได้ตอบคำชวน และไวยากรณ์ไม่เหมาะ"),
       ("Lunch at our school always starts at noon.", "บอกข้อมูลเวลา ไม่ได้ตอบรับหรือปฏิเสธ")],
      [("ระบุ: Let's + V = ชวนทำด้วยกัน", "grab lunch = ไปกินข้าวกลางวันแบบเร็ว ๆ"),
       ("ตอบรับอย่างเป็นธรรมชาติ", "Sounds good. I'm starving!")],
      ["Let's... เป็นการชวนหรือสั่ง",
       "grab lunch หมายถึงอะไรในภาษาพูด",
       "ตัวเลือกไหนตอบรับคำชวน"],
      "ตอบ Sounds good. I'm starving! เพราะตอบรับคำชวนไปกินข้าวอย่างเป็นธรรมชาติ",
      diff=1, sec=25, tags=["word_match_trap"]),
    q(d("A: I'm organizing a beach clean-up next Saturday. Would you be interested in joining?", "B: I'd really like to help, but I've already promised to help my aunt at her shop that day.", "A: ______"),
      "No problem. Maybe next time!",
      [("Why don't you like the beach?", "B ไม่ได้บอกว่าไม่ชอบทะเล ตีความเหตุผลผิด"),
       ("Great! See you on Saturday.", "ทำเหมือน B ตอบรับ ทั้งที่ B ปฏิเสธ"),
       ("Then your aunt should come and clean the beach with us, too.", "ไม่เกี่ยวและไม่สุภาพ")],
      [("ระบุ: B ปฏิเสธอย่างสุภาพพร้อมเหตุผล", "A ต้องตอบรับการปฏิเสธนั้น"),
       ("คำตอบที่ดี: แสดงว่าเข้าใจ และเปิดโอกาสครั้งหน้า", "No problem. Maybe next time!")],
      ["B ตอบรับหรือปฏิเสธคำชวน",
       "เมื่ออีกฝ่ายปฏิเสธอย่างสุภาพ เราควรตอบอย่างไร",
       "ตัดตัวเลือกที่เข้าใจคำตอบของ B ผิด"],
      "ตอบ No problem. Maybe next time! เพราะ B ปฏิเสธอย่างสุภาพ A จึงควรแสดงความเข้าใจและเปิดโอกาสครั้งหน้า",
      diff=3, sec=45, reading="medium"),
]
P += [
 N(d("A: We're having a board-game night on Friday. Want to join us?","B: ______"),"I'd love to. What time should I come?",[("I joined the board last year.","จับคำ board แต่คนละความหมาย"),("Friday wants to join us.","ทำวันเป็นผู้กระทำ"),("The game is having a night.","เรียงคำจากโจทย์แต่ไม่ตอบคำเชิญ")],"เป็นคำเชิญแบบไม่เป็นทางการ","ตอบรับและถามรายละเอียดต่อเหมาะกับคำเชิญ",3,["word_match_trap"]),
 N(d("A: Would you like to come to the opening? I know it's short notice.","B: ______"),"I wish I could, but I'm covering a shift that evening.",[("Yes, the notice should be shorter.","จับ short notice เป็นความยาวประกาศ"),("I wouldn't like the opening hours.","ใช้ wouldn't like เป็นความไม่ชอบแทนการปฏิเสธคำเชิญ"),("I could come if you hadn't invited me.","เงื่อนไขขัดกับความหมาย")],"ผู้พูดเชิญและยอมรับว่าแจ้งกระชั้น","ปฏิเสธอย่างสุภาพพร้อมเหตุผลที่ชัดและไม่เปิดความหวังผิด",5,["would_like_as_like"]),
]
save(tid, "TGAT1", "mcq4", P, lesson=L)

# ============================================================ apology_thanks
tid = B + "apology_thanks"
L = lesson(tid, "ขอโทษ ขอบคุณ และการตอบกลับ",
    "ตอบคำขอบคุณด้วย You're welcome ตอบคำขอโทษด้วย That's OK — สลับกันไม่ได้",
    objectives=["ตอบคำขอบคุณได้หลายระดับความเป็นทางการ", "ตอบคำขอโทษได้ทั้งกรณีไม่ถือสาและกรณีที่ยังต้องแก้ไข", "ไม่สลับคำตอบของขอบคุณกับขอโทษ"],
    prereq=FOUND, nxt=[B + "opinion_agreement"],
    blocks=[
        hook("ตัวลวงยอดนิยมในหัวข้อนี้คือ **คำตอบที่ถูก แต่ใช้ผิดสถานการณ์** เช่น ตอบคำขอโทษด้วย \"You're welcome.\""),
        concept("คู่คำพูดที่ต้องจับให้ถูก",
                "| ประโยคแรก | คำตอบ |\n|---|---|\n"
                "| Thank you. / Thanks a lot. | You're welcome. / No problem. / My pleasure. / Anytime. |\n"
                "| I really appreciate your help. | I'm glad I could help. |\n"
                "| I'm sorry. / Sorry about that. | That's OK. / No worries. / Don't worry about it. |\n"
                "| I'm so sorry I'm late. | It's all right. We just started. |\n"
                "| Sorry to hear that. (เห็นใจ) | Thanks. |\n\n"
                "**ระวัง:** \"I'm sorry to hear that.\" ไม่ใช่การขอโทษ แต่เป็นการ **แสดงความเห็นใจ**"),
        technique("ถามว่าประโยคแรกคือ ขอบคุณ ขอโทษ หรือเห็นใจ",
                  "ทุกข้อที่มีคำว่า thank, sorry, appreciate",
                  "ถ้าความผิดพลาดยังต้องแก้ อย่าเลือกแค่ \"No worries.\" ให้ดูว่ามีตัวเลือกที่แก้ปัญหาด้วยไหม",
                  "ระบุหน้าที่ก่อน แล้วจับคู่คำตอบจากตาราง ถ้าเป็นการขอโทษที่ทำให้เกิดความเสียหาย คำตอบที่ดีมักรับคำขอโทษพร้อมบอกว่าจะจัดการอย่างไร",
                  tip="ขอบคุณ → welcome · ขอโทษ → that's OK · เห็นใจ → thanks"),
        example("ตัวอย่างที่ 1",
                d("A: Sorry, I think I took your seat by mistake.", "B: ______"),
                [("ระบุ: A ขอโทษ", "คำตอบต้องรับคำขอโทษ"),
                 ("เลือก No worries. + ข้อมูลที่ช่วย", "\"No worries. Mine is the next one.\"")],
                "\"No worries. Mine is the next one.\""),
        pitfall("ตอบคำขอโทษด้วย You're welcome",
                "A: I'm sorry I broke your pen. → B: \"You're welcome.\"",
                "You're welcome ใช้ตอบคำขอบคุณ ไม่ใช่คำขอโทษ",
                "\"That's OK. I have another one.\"",
                "welcome_for_sorry"),
        pitfall("เข้าใจ sorry to hear ว่าเป็นการขอโทษ",
                "A: I'm sorry to hear about your grandmother. → B: \"That's OK, it's not your fault.\"",
                "A ไม่ได้ขอโทษ แต่แสดงความเสียใจด้วย คำตอบที่เหมาะคือขอบคุณ",
                "\"Thank you. That's very kind of you.\"",
                "sorry_to_hear_as_apology"),
        summary("ขอบคุณ → You're welcome / No problem / My pleasure",
                "ขอโทษ → That's OK / No worries / Don't worry about it",
                "Sorry to hear that = เห็นใจ → ตอบ Thank you",
                "ความผิดที่ยังต้องแก้ ให้เลือกคำตอบที่แก้ปัญหาด้วย"),
        check(d("A: Thank you so much for helping me move yesterday.", "B: ______"),
              ["That's OK. It's not your fault.", "My pleasure. Let me know if you need anything else.", "Sorry, I was busy.", "Yes, you moved yesterday."], 1,
              "ตอบคำขอบคุณด้วย My pleasure ตัวเลือกแรกเป็นคำตอบของคำขอโทษ"),
    ],
    patterns=["สลับคำตอบของขอบคุณกับขอโทษเป็นตัวลวง", "ใช้ sorry to hear that เพื่อดักคนที่คิดว่าเป็นการขอโทษ"],
    sources=["ผังการสอบ TGAT1 จาก mytcas.com (พาร์ทการพูด ส่วนการถาม-ตอบ)", "ประโยคและบทสนทนาแต่งขึ้นใหม่เพื่อการฝึก"],
)
P = [
    q(d("A: Thanks for lending me your notes.", "B: ______"),
      "No problem. I hope they help.",
      [("That's OK. It wasn't your fault.", "เป็นคำตอบของคำขอโทษ ไม่ใช่คำขอบคุณ"),
       ("Yes, I lent them.", "ทวนข้อเท็จจริงแต่ไม่ได้ตอบคำขอบคุณ"),
       ("Sorry, they are my notes.", "ขอโทษโดยไม่มีเหตุผล")],
      [("ระบุ: A ขอบคุณ", "ต้องตอบคำขอบคุณ"),
       ("No problem. = ด้วยความยินดี แบบไม่ทางการ", "เพิ่ม I hope they help. ให้เป็นธรรมชาติ")],
      ["ประโยคของ A คือขอบคุณหรือขอโทษ",
       "คำตอบของคำขอบคุณแบบไม่ทางการมีอะไรบ้าง",
       "ตัดตัวเลือกที่เป็นคำตอบของคำขอโทษ"],
      "ตอบ No problem. I hope they help. เพราะ A ขอบคุณ คำตอบที่เหมาะคือรับคำขอบคุณ",
      diff=1, sec=25, tags=["welcome_for_sorry"]),
    q(d("A: I'm sorry I forgot to call you back last night.", "B: ______"),
      "Don't worry about it. We can talk now.",
      [("You're welcome. You can call me back anytime you like.", "You're welcome ใช้ตอบคำขอบคุณ ไม่ใช่คำขอโทษ"),
       ("I'm sorry, too. I forgot.", "B ไม่ได้ทำผิดอะไร การขอโทษกลับไม่เข้ากับสถานการณ์"),
       ("Yes, you forgot last night.", "ทวนความผิดของ A ซ้ำ ไม่ได้รับคำขอโทษ")],
      [("ระบุ: A ขอโทษ", "ต้องรับคำขอโทษ"),
       ("Don't worry about it. + เสนอคุยตอนนี้", "รับคำขอโทษและแก้ปัญหาได้ทันที")],
      ["A ขอบคุณหรือขอโทษ",
       "You're welcome ใช้ตอบอะไร",
       "คำตอบที่ดีรับคำขอโทษและพาบทสนทนาต่อไปได้"],
      "ตอบ Don't worry about it. We can talk now. เพราะรับคำขอโทษอย่างใจกว้างและพาบทสนทนาไปต่อ",
      diff=2, sec=30, tags=["welcome_for_sorry"]),
    q(d("A: I heard you didn't pass the audition. I'm sorry to hear that.", "B: ______"),
      "Thanks. I'll try again next year.",
      [("That's OK. It's not your fault that I didn't pass.", "ตีความ sorry to hear that ว่า A ขอโทษ ทั้งที่ A แสดงความเห็นใจ"),
       ("You're welcome.", "เป็นคำตอบของคำขอบคุณ"),
       ("Yes, you heard it wrong.", "ขัดกับข้อเท็จจริงในบทสนทนา")],
      [("ระบุ: I'm sorry to hear that = แสดงความเห็นใจ", "ไม่ใช่การขอโทษ"),
       ("ตอบด้วยการขอบคุณที่เห็นใจ", "Thanks. และบอกว่าจะพยายามใหม่")],
      ["A ทำอะไรผิดไหม ทำไมถึงพูดว่า sorry",
       "sorry to hear that ใช้เพื่อขอโทษหรือเพื่อแสดงความเห็นใจ",
       "คนที่ได้รับความเห็นใจควรตอบอย่างไร"],
      "ตอบ Thanks. I'll try again next year. เพราะ A แสดงความเห็นใจ ไม่ได้ขอโทษ คำตอบที่เหมาะคือขอบคุณ",
      diff=3, sec=40, tags=["sorry_to_hear_as_apology"]),
    q(d("A: I really appreciate you staying late to help me finish the report.", "B: ______"),
      "I'm glad I could help.",
      [("I appreciate it, too.", "ทวนคำว่า appreciate แต่ทำให้ดูเหมือน B ก็ขอบคุณ A"),
       ("Sorry, I stayed too late.", "ขอโทษโดยไม่มีเหตุผล"),
       ("The report was finished late.", "บอกข้อเท็จจริงแต่ไม่ได้ตอบคำขอบคุณ")],
      [("ระบุ: I really appreciate... = ขอบคุณอย่างจริงใจ", "ต้องตอบคำขอบคุณ"),
       ("I'm glad I could help. = ยินดีที่ช่วยได้", "เหมาะกับการตอบคำขอบคุณที่จริงจัง")],
      ["appreciate มีความหมายใกล้กับคำไหน",
       "ประโยคของ A คือขอบคุณหรือขอโทษ",
       "คำตอบของคำขอบคุณที่จริงจังคืออะไร"],
      "ตอบ I'm glad I could help. เพราะ A ขอบคุณอย่างจริงใจ คำตอบที่เหมาะคือบอกว่ายินดีที่ช่วยได้",
      diff=2, sec=30, tags=["word_match_trap"]),
    q(d("A: Excuse me, I'm afraid you've charged me twice for the same coffee.", "B: ______"),
      "I'm so sorry. Let me refund it now.",
      [("You're welcome. Enjoy your coffee and have a nice day.", "ตอบเหมือนลูกค้าขอบคุณ ไม่ได้รับรู้ปัญหา"),
       ("That's OK. It happens.", "เป็นคำพูดของคนที่ถูกขอโทษ แต่ในสถานการณ์นี้ร้านเป็นฝ่ายผิด"),
       ("I'm afraid, too.", "ทวนคำว่า afraid โดยไม่มีความหมาย")],
      [("ระบุ: ลูกค้าแจ้งข้อผิดพลาด (I'm afraid... = แจ้งข่าวไม่ดีอย่างสุภาพ)", "ร้านเป็นฝ่ายผิด"),
       ("คำตอบที่ดี: ขอโทษ + แก้ไขทันที", "Let me refund it for you right away.")],
      ["ใครเป็นฝ่ายผิดในสถานการณ์นี้",
       "I'm afraid... ในที่นี้แปลว่ากลัว หรือเป็นการแจ้งเรื่องไม่ดีอย่างสุภาพ",
       "ฝ่ายผิดควรทำอะไรนอกจากขอโทษ"],
      "ตอบ I'm so sorry. Let me refund it now. เพราะร้านเป็นฝ่ายผิด ต้องขอโทษและแก้ไขทันที",
      diff=3, sec=40, reading="medium", tags=["welcome_for_sorry"]),
    q(d("A: Oops! Sorry, I spilled some water on your desk.", "B: ______"),
      "It's OK. Let's wipe it up.",
      [("Thank you. That's kind of you.", "ตอบเหมือนได้รับความช่วยเหลือ"),
       ("You're welcome to spill it.", "ใช้ You're welcome ผิดความหมายและไม่สมเหตุผล"),
       ("Sorry to hear that.", "เป็นการแสดงความเห็นใจเรื่องร้ายของคนอื่น ไม่เข้ากับสถานการณ์")],
      [("ระบุ: A ขอโทษที่ทำน้ำหก", "ต้องรับคำขอโทษ"),
       ("รับคำขอโทษ + ช่วยกันจัดการปัญหา", "It's OK. Let's wipe it up.")],
      ["A ขอโทษเรื่องอะไร",
       "คำตอบรับคำขอโทษแบบไม่ถือสาคืออะไร",
       "คำตอบที่ดีแก้ปัญหาที่เกิดขึ้นด้วยไหม"],
      "ตอบ It's OK. Let's wipe it up. เพราะรับคำขอโทษและชวนกันจัดการปัญหาที่เกิดขึ้น",
      diff=1, sec=25, tags=["welcome_for_sorry"]),
]
P += [
 N(d("A: I'm sorry I spilled coffee on your draft.","B: ______"),"It's okay. I saved another copy.",[("You're welcome to spill it.","ใช้ You're welcome ผิดกับคำขอโทษ"),("I'm sorry to hear your coffee.","ใช้วลีแสดงความเห็นใจผิดบริบท"),("Thanks for the coffee draft.","ขอบคุณสิ่งที่สร้างความเสียหาย")],"เป็นการขอโทษจากอุบัติเหตุ","ตอบรับคำขอโทษและบอกว่ามีสำเนาสำรอง",3,["welcome_for_sorry"]),
 N(d("A: Thank you for staying late to fix the figures.","B: ______"),"No problem. I'm glad we caught the error in time.",[("Never mind; the figures thanked me.","Never mind ไม่รับคำขอบคุณและประธานผิด"),("I'm sorry to hear that you stayed.","แสดงความเสียใจกับการช่วยเหลือ"),("You're welcome, so you owe me one.","เริ่มรับคำขอบคุณแต่ลงท้ายกดดันไม่เหมาะกับงาน")],"เป็นคำขอบคุณในบริบททำงานร่วมกัน","รับคำขอบคุณและเชื่อมกับผลดีของทีมอย่างเป็นมืออาชีพ",5,["welcome_for_sorry"]),
]
save(tid, "TGAT1", "mcq4", P, lesson=L)

# ============================================================ opinion_agreement
tid = B + "opinion_agreement"
L = lesson(tid, "ถามความเห็น เห็นด้วย และไม่เห็นด้วย",
    "เห็นด้วยกับประโยคปฏิเสธต้องใช้ neither/me neither และไม่เห็นด้วยอย่างสุภาพต้องมีคำนำก่อนแย้ง",
    objectives=["ถามความเห็นได้หลายรูปแบบ", "เห็นด้วยกับประโยคบอกเล่าและปฏิเสธได้ถูก", "ไม่เห็นด้วยอย่างสุภาพ"],
    prereq=FOUND, nxt=[B + "wh_question_matching"],
    blocks=[
        hook("\"I don't like horror movies.\" ถ้าเห็นด้วย ต้องตอบ **\"Me neither.\"** ไม่ใช่ \"Me too.\" "
             "กับดักนี้ออกบ่อยมากเพราะภาษาไทยใช้ \"ฉันด้วย\" ได้ทั้งสองแบบ"),
        concept("ถามความเห็น เห็นด้วย ไม่เห็นด้วย",
                "**ถามความเห็น:** What do you think of/about...? / How do you feel about...? / What's your opinion on...?\n\n"
                "**เห็นด้วย:**\n- กับประโยคบอกเล่า: Me too. / So do I. / I agree. / Exactly.\n- กับประโยคปฏิเสธ: **Me neither. / Neither do I. / I don't either.**\n\n"
                "**ไม่เห็นด้วยอย่างสุภาพ:** I see your point, but... / I'm not sure about that. / I see what you mean, but..."),
        technique("ดูว่าประโยคแรกบอกเล่าหรือปฏิเสธ",
                  "ทุกข้อที่ให้เลือกคำตอบแสดงการเห็นด้วย",
                  "ถ้าผู้พูดถามความเห็น ไม่ได้บอกความเห็น ให้ตอบด้วยความเห็นของเรา ไม่ใช่ Me too",
                  "มี not / don't / never อยู่ในประโยคแรกไหม ถ้ามี คำตอบเห็นด้วยต้องเป็น neither / either",
                  tip="บอกเล่า → too/so · ปฏิเสธ → neither/either"),
        example("ตัวอย่างที่ 1",
                d("A: I can't stand waiting in long lines.", "B: ______ They're so annoying."),
                [("ประโยคแรกเป็นปฏิเสธ (can't)", "เห็นด้วยต้องใช้ neither"),
                 ("Neither can I. ใช้กริยาช่วยเดียวกับ A", "can't → Neither can I")],
                "\"Neither can I.\""),
        pitfall("ตอบ Me too กับประโยคปฏิเสธ",
                "A: I don't eat spicy food. → B: \"Me too.\"",
                "A พูดประโยคปฏิเสธ Me too ใช้กับประโยคบอกเล่า",
                "\"Me neither.\" / \"Neither do I.\"",
                "too_neither_confusion"),
        pitfall("ไม่เห็นด้วยแบบห้วน",
                "A: I think online classes are better. → B: \"You're wrong.\"",
                "ความหมายถูก แต่ไม่สุภาพ ข้อสอบมักถือว่าไม่เหมาะสม",
                "\"I see your point, but I learn better in a classroom.\"",
                "rude_disagreement"),
        summary("ถามความเห็น: What do you think of...?",
                "เห็นด้วยกับบอกเล่า: Me too / So do I",
                "เห็นด้วยกับปฏิเสธ: Me neither / Neither do I",
                "ไม่เห็นด้วย: I see your point, but..."),
        check(d("A: I've never been to Japan.", "B: ______"),
              ["Me too.", "Neither have I.", "So have I.", "I have never, too."], 1,
              "ประโยคของ A เป็นปฏิเสธ (never) และใช้ have เห็นด้วยต้องตอบ Neither have I."),
    ],
    patterns=["ให้ประโยคปฏิเสธแล้วมี Me too เป็นตัวลวง", "ถามความเห็นแล้วมีตัวลวงเป็นคำตอบเห็นด้วย", "ไม่เห็นด้วยแบบสุภาพกับแบบห้วน"],
    sources=["ผังการสอบ TGAT1 จาก mytcas.com (พาร์ทการพูด ส่วนการถาม-ตอบ)", "ประโยคและบทสนทนาแต่งขึ้นใหม่เพื่อการฝึก"],
)
P = [
    q(d("A: I really enjoyed the concert last night.", "B: ______ The band was amazing."),
      "So did I.",
      [("Neither did I.", "ใช้กับประโยคปฏิเสธ แต่ A พูดประโยคบอกเล่า"),
       ("So do I.", "ใช้กริยาช่วยผิดกาล A พูดอดีต (enjoyed) ต้องใช้ did"),
       ("I did too not.", "ไวยากรณ์ผิด")],
      [("ประโยคของ A บอกเล่า และเป็นอดีต", "enjoyed → กริยาช่วย did"),
       ("เห็นด้วยกับประโยคบอกเล่า", "So did I.")],
      ["ประโยคของ A บอกเล่าหรือปฏิเสธ",
       "กริยาของ A เป็นกาลอะไร ต้องใช้กริยาช่วยตัวไหน",
       "เห็นด้วยกับประโยคบอกเล่าใช้ so หรือ neither"],
      "ตอบ So did I. เพราะเห็นด้วยกับประโยคบอกเล่าในอดีต ต้องใช้ so และกริยาช่วย did",
      diff=2, sec=30, tags=["too_neither_confusion"]),
    q(d("A: I don't think the test was very difficult.", "B: ______ I finished early."),
      "Neither do I.",
      [("I do too.", "ใช้กับประโยคบอกเล่า แต่ A พูดประโยคปฏิเสธ"),
       ("Me too. It was quite easy.", "ใช้กับประโยคบอกเล่า แต่ A พูดประโยคปฏิเสธ"),
       ("So do I.", "ใช้กับประโยคบอกเล่า ความหมายจะกลับเป็นคิดว่ายาก ขัดกับ I finished early")],
      [("ประโยคของ A ปฏิเสธ (don't think)", "เห็นด้วยต้องใช้ either/neither"),
       ("ข้อความต่อท้าย I finished early. ยืนยันว่าเห็นด้วยว่าไม่ยาก", "Neither do I. เป็นรูปตอบรับที่เป็นธรรมชาติ")],
      ["ประโยคของ A มีคำปฏิเสธไหม",
       "รูปตอบรับประโยคปฏิเสธสามารถขึ้นต้นด้วย neither ได้",
       "ประโยค I finished early บอกว่า B คิดว่าข้อสอบยากหรือง่าย"],
      "ตอบ Neither do I. เพราะ A พูดประโยคปฏิเสธ การเห็นด้วยจึงใช้ neither และสอดคล้องกับ I finished early",
      diff=2, sec=30, tags=["too_neither_confusion"]),
    q(d("A: What do you think of the new school uniform?", "B: ______"),
      "I like the color, but it's too thick.",
      [("Me too. I think so.", "A ถามความเห็น ไม่ได้บอกความเห็นให้เห็นด้วย"),
       ("I think of it every day when I get dressed for school.", "ตีความ think of ว่าคิดถึง ไม่ได้ให้ความเห็น"),
       ("Yes, I do.", "ตอบเหมือนคำถาม yes/no แต่ A ถามด้วย What")],
      [("ระบุ: What do you think of...? = ถามความเห็น", "ต้องตอบด้วยความเห็นของ B"),
       ("คำตอบที่ให้ความเห็นจริง", "I like the color, but the fabric is too thick...")],
      ["A บอกความเห็นหรือถามความเห็น",
       "What do you think of...? ต้องตอบด้วยอะไร",
       "ตัดตัวเลือกที่ตอบเหมือนคำถาม yes/no"],
      "ตอบ I like the color, but it's too thick. เพราะ A ถามความเห็น B จึงต้องตอบด้วยความเห็นของตัวเอง",
      diff=2, sec=35, tags=["literal_translation"]),
    q(d("A: I think we should cancel the sports day because of the heat.", "B: ______"),
      "I see your point, but we could move it to the morning.",
      [("You're completely wrong. Sports day is the best day of the whole year.", "ไม่เห็นด้วยแบบห้วนเกินไป ไม่สุภาพ"),
       ("Me neither. It's far too hot to do any sports outside.", "ใช้ Me neither กับประโยคบอกเล่า และความหมายไม่ชัด"),
       ("Yes, the sports day is hot.", "ทวนคำว่า hot ไม่ได้ให้ความเห็นว่าควรยกเลิกไหม")],
      [("ระบุ: A เสนอความเห็น", "B ตอบเห็นด้วยหรือไม่เห็นด้วยก็ได้"),
       ("ตัวเลือกที่ดีที่สุด: ไม่เห็นด้วยอย่างสุภาพพร้อมเสนอทางเลือก", "I see your point, but..."),
       ("ตัดตัวที่ห้วนหรือผิดไวยากรณ์", "เหลือตัวที่สุภาพและสมเหตุผล")],
      ["A เสนออะไร",
       "ถ้า B ไม่เห็นด้วย ควรพูดอย่างไรให้สุภาพ",
       "I see your point, but... ใช้ทำอะไร"],
      "ตอบ I see your point, but we could move it to the morning. เพราะไม่เห็นด้วยอย่างสุภาพและเสนอทางเลือกที่สมเหตุผล",
      diff=3, sec=40, tags=["rude_disagreement"]),
    q(d("A: I can't believe how expensive concert tickets are these days.", "B: ______ I paid almost two thousand baht for mine."),
      "I know! The prices are ridiculous.",
      [("Me neither. They're cheap.", "ใช้ neither ได้ แต่ต่อด้วย They're cheap ขัดกับประโยคถัดไปที่บอกว่าจ่ายแพง"),
       ("Yes, I can believe.", "ตีความ can't believe ตรงตัว ทั้งที่เป็นสำนวนแสดงความประหลาดใจ"),
       ("So can I.", "ใช้ so กับประโยคปฏิเสธ can't")],
      [("I can't believe how expensive... = สำนวนบ่นว่าแพงมาก", "ไม่ได้ปฏิเสธความเชื่อจริง ๆ"),
       ("ประโยคถัดไปของ B ยืนยันว่าเห็นด้วยว่าแพง", "I know! The prices are ridiculous. เป็นการเห็นด้วยแบบภาษาพูดที่ชัดเจน")],
      ["I can't believe how expensive... ใช้บ่นหรือบอกว่าไม่เชื่อจริง ๆ",
       "ประโยคที่ B พูดต่อบอกว่า B คิดว่าแพงหรือถูก",
       "ภาษาพูดเห็นด้วยแบบกระตือรือร้นพูดว่าอะไรได้บ้าง"],
      "ตอบ I know! The prices are ridiculous. เพราะ A บ่นว่าตั๋วแพง และ B เห็นด้วยตามที่ยืนยันในประโยคถัดไป",
      diff=4, sec=45, tags=["literal_translation"]),
    q(d("A: How do you feel about having homework on weekends?", "B: ______"),
      "Honestly, I'd prefer to keep my weekends free.",
      [("I feel fine, thank you.", "ตอบเหมือนถูกถามว่าสบายดีไหม"),
       ("Me too. I agree with you.", "A ถามความเห็น ยังไม่ได้บอกความเห็นให้เห็นด้วย"),
       ("On weekends I usually have a lot of homework from every subject.", "บอกข้อเท็จจริง ไม่ได้ให้ความรู้สึกหรือความเห็น")],
      [("ระบุ: How do you feel about...? = ถามความรู้สึก/ความเห็น", "ไม่ใช่ถามสุขภาพ"),
       ("ตอบด้วยความเห็นของตัวเอง", "I'd prefer to keep my weekends free.")],
      ["How do you feel about... ถามสุขภาพหรือถามความเห็น",
       "A บอกความเห็นของตัวเองแล้วหรือยัง",
       "หาตัวเลือกที่ให้ความเห็นจริง"],
      "ตอบ Honestly, I'd prefer to keep my weekends free. เพราะ A ถามความรู้สึกต่อเรื่องการบ้านวันหยุด B จึงต้องให้ความเห็น",
      diff=1, sec=30, tags=["literal_translation"]),
]
P += [
 N(d("A: I think the workshop should include more practice time.","B: ______"),"I agree. The last activity felt rushed.",[("So do the workshop.","ใช้ so do ผิดโครงสร้างและความหมาย"),("Neither is the practice.","ใช้ neither กับข้อความบอกเล่าเชิงบวก"),("Yes, time includes workshops.","สลับความสัมพันธ์ของคำ")],"เป็นการขอความเห็นต่อข้อเสนอ","แสดงความเห็นด้วยและให้เหตุผลที่ตรงประเด็น",3,["too_neither_confusion"]),
 N(d("A: The new schedule is more efficient, but it leaves no break between labs.","B: ______"),"That's true. It saves time overall, though the lack of a break may be a problem.",[("I completely disagree; efficiency is always bad.","ปฏิเสธสุดโต่งและบิดประเด็น"),("Me too, the schedule left yesterday.","ใช้ me too กับข้อสังเกตและจับ leaves เป็นออกไป"),("Neither do I have a laboratory schedule.","เปลี่ยนเป็นการครอบครองตาราง ไม่ตอบการประเมิน")],"ข้อความมีทั้งข้อดีและข้อกังวล","คำตอบยอมรับสองด้านแทนเลือกเห็นด้วยหรือคัดค้านทั้งหมด",5,["rude_disagreement"]),
]
save(tid, "TGAT1", "mcq4", P, lesson=L)

# ============================================================ wh_question_matching
tid = B + "wh_question_matching"
L = lesson(tid, "จับคู่คำถาม Wh- กับชนิดข้อมูลที่ต้องตอบ",
    "คำถามแต่ละคำต้องการข้อมูลคนละชนิด ตัวลวงมักตอบเรื่องเดียวกันแต่ผิดชนิดข้อมูล",
    objectives=["บอกได้ว่าคำถาม Wh- แต่ละคำต้องการข้อมูลแบบไหน", "แยก How long / How often / How far / How much ได้", "ตัดตัวลวงที่ตอบผิดชนิดข้อมูล"],
    prereq=FOUND, nxt=[B + "yesno_and_tag"],
    blocks=[
        hook("\"How often do you go to the gym?\" ถ้าตอบ \"For two hours.\" ผิด เพราะถามความถี่ ไม่ได้ถามระยะเวลา "
             "ข้อนี้เป็นจุดที่ทำคะแนนได้ง่ายถ้าจับชนิดข้อมูลให้ถูก"),
        concept("คำถามกับชนิดข้อมูล",
                "| คำถาม | ต้องการ | ตัวอย่างคำตอบ |\n|---|---|---|\n"
                "| When | เวลา | Next Monday. |\n| Where | สถานที่ | At the station. |\n| Who | คน | My sister. |\n"
                "| Why | เหตุผล | Because it's cheaper. |\n| Which | เลือกจากตัวเลือกที่มี | The blue one. |\n"
                "| How | วิธี / สภาพ | By bus. / Pretty good. |\n| How long | ระยะเวลา | About two hours. |\n"
                "| How often | ความถี่ | Twice a week. |\n| How far | ระยะทาง | About 5 kilometers. |\n"
                "| How much / How many | ปริมาณ ราคา / จำนวน | 200 baht. / Three. |\n| Whose | เจ้าของ | It's Tom's. |"),
        technique("วงคำถามให้ครบ 2 คำ",
                  "เมื่อเจอคำถามที่ขึ้นต้นด้วย How",
                  "คำถามทางอ้อมอย่าง Do you know where...? ยังต้องตอบด้วยข้อมูลของ where แม้ขึ้นต้นด้วย Do",
                  "อย่าดูแค่ How ให้ดูคำที่ตามมาด้วย (long/often/far/much/many) แล้วหาคำตอบที่มีชนิดข้อมูลตรงนั้น",
                  tip="How + คำถัดไป = ชนิดข้อมูล"),
        example("ตัวอย่างที่ 1",
                d("A: How long does it take to get to the airport from here?", "B: ______"),
                [("How long + take = ใช้เวลานานเท่าไร", "ต้องการระยะเวลา"),
                 ("ตัดตัวที่ตอบระยะทาง วิธีการ หรือความถี่", "เหลือ About 45 minutes by taxi.")],
                "\"About 45 minutes by taxi.\""),
        pitfall("สับสน How long กับ How often",
                "A: How often do you exercise? → B: \"For an hour.\"",
                "How often ถามความถี่ ไม่ได้ถามว่าแต่ละครั้งนานเท่าไร",
                "\"Three times a week.\"",
                "wh_type_mismatch"),
        summary("ดูคำถามให้ครบ โดยเฉพาะ How + คำถัดไป",
                "How long = ระยะเวลา · How often = ความถี่ · How far = ระยะทาง",
                "Which = เลือกจากตัวเลือกที่มี · Whose = เจ้าของ",
                "ตัวลวงมักพูดเรื่องเดียวกันแต่ผิดชนิดข้อมูล"),
        check(d("A: How far is the nearest hospital?", "B: ______"),
              ["About ten minutes ago.", "It's about three kilometers from here.", "It's very good.", "Twice a day."], 1,
              "How far ถามระยะทาง"),
    ],
    patterns=["คำถาม How ที่ต้องแยกชนิดข้อมูล", "ตัวลวงพูดเรื่องเดียวกันแต่ผิดชนิดข้อมูล", "คำถามทางอ้อม Do you know + Wh-"],
    sources=["ผังการสอบ TGAT1 จาก mytcas.com (พาร์ทการพูด ส่วนการถาม-ตอบ)", "ประโยคและบทสนทนาแต่งขึ้นใหม่เพื่อการฝึก"],
)
P = [
    q(d("A: How often do you visit your grandparents?", "B: ______"),
      "About once a month.",
      [("For three days, usually during the school holidays.", "ตอบระยะเวลาที่อยู่ ไม่ใช่ความถี่"),
       ("By train.", "ตอบวิธีเดินทาง (How) ไม่ใช่ความถี่"),
       ("In Chiang Rai.", "ตอบสถานที่ (Where)")],
      [("How often = บ่อยแค่ไหน", "ต้องการความถี่"),
       ("หาคำตอบที่บอกความถี่", "About once a month.")],
      ["How often ถามข้อมูลชนิดไหน",
       "คำบอกความถี่มีรูปแบบอย่างไร เช่น ...a week",
       "ตัดตัวเลือกที่ตอบระยะเวลาหรือสถานที่"],
      "ตอบ About once a month. เพราะ How often ถามความถี่",
      diff=1, sec=25, tags=["wh_type_mismatch"]),
    q(d("A: Which bus goes to Riverside Mall?", "B: ______"),
      "Bus number 25.",
      [("Because it's faster.", "ตอบเหตุผล (Why)"),
       ("Every 15 minutes during the morning rush hour.", "ตอบความถี่ของรถ (How often)"),
       ("Yes, it goes there.", "ตอบเหมือนคำถาม yes/no")],
      [("Which = เลือกอันไหน", "ต้องบอกว่ารถสายไหน"),
       ("คำตอบระบุสายรถ", "Bus number 25.")],
      ["Which ถามให้ระบุอะไร",
       "คำถามนี้ตอบด้วย Yes/No ได้ไหม",
       "หาตัวเลือกที่บอกว่ารถคันไหน"],
      "ตอบ Bus number 25. เพราะ Which ถามให้ระบุว่ารถสายไหน",
      diff=1, sec=25, tags=["wh_type_mismatch"]),
    q(d("A: How long have you been learning the guitar?", "B: ______"),
      "Since I was twelve.",
      [("Every Saturday.", "ตอบความถี่ ไม่ใช่ระยะเวลาที่เรียนมา"),
       ("It's about one meter long.", "ตีความ long ว่าความยาวของกีตาร์"),
       ("From my teacher.", "ตอบว่าเรียนจากใคร ไม่ใช่นานเท่าไร")],
      [("How long + have been V-ing = ทำมานานเท่าไรแล้ว", "ต้องการระยะเวลาจนถึงปัจจุบัน"),
       ("Since + จุดเริ่มต้น บอกระยะเวลาได้", "Since I was twelve.")],
      ["How long ในประโยคนี้ถามความยาวหรือระยะเวลา",
       "have been learning บอกว่ากิจกรรมยังทำอยู่ถึงตอนนี้ไหม",
       "since ใช้บอกอะไร"],
      "ตอบ Since I was twelve. เพราะคำถามถามว่าเรียนมานานเท่าไร Since บอกจุดเริ่มต้นจนถึงปัจจุบัน",
      diff=2, sec=30, tags=["wh_type_mismatch"]),
    q(d("A: Do you know where the lost-and-found office is?", "B: ______"),
      "On the second floor, by the elevator.",
      [("Yes, I know.", "ตอบแค่ว่ารู้ แต่ไม่ได้ให้ข้อมูลที่ A ต้องการจริง"),
       ("I lost my wallet.", "ตอบเรื่องที่ตัวเองทำของหาย ไม่ได้บอกที่ตั้ง"),
       ("It opens at 9 a.m. and closes at 5 p.m. from Monday to Friday.", "ตอบเวลาเปิด ไม่ใช่สถานที่")],
      [("Do you know where...? = คำถามทางอ้อม", "จริง ๆ ต้องการรู้ว่าอยู่ที่ไหน"),
       ("ตอบด้วยข้อมูลสถานที่", "On the second floor, by the elevator.")],
      ["A อยากรู้แค่ว่า B รู้หรือไม่ หรืออยากรู้ที่ตั้งจริง ๆ",
       "คำถามนี้มีคำว่า where อยู่ข้างใน ต้องการข้อมูลชนิดไหน",
       "การตอบแค่ Yes, I know. ช่วย A ได้ไหม"],
      "ตอบ On the second floor, by the elevator. เพราะเป็นคำถามทางอ้อมที่ต้องการรู้สถานที่ ตอบแค่ Yes ไม่ได้ช่วย A",
      diff=3, sec=35, tags=["wh_type_mismatch"]),
    q(d("A: Whose laptop is this on the table?", "B: ______"),
      "I think it's Pim's. She was sitting there.",
      [("It's a new laptop. It looks really expensive.", "บอกลักษณะ ไม่ได้บอกเจ้าของ"),
       ("On the table.", "ตอบสถานที่ซึ่ง A บอกไว้แล้ว"),
       ("Who is Pim?", "ถามกลับแทนการตอบ")],
      [("Whose = ของใคร", "ต้องการเจ้าของ"),
       ("คำตอบระบุเจ้าของพร้อมเหตุผล", "I think it's Pim's.")],
      ["Whose ถามอะไร",
       "รูป 's หลังชื่อหมายถึงอะไร",
       "ตัดตัวเลือกที่ตอบลักษณะหรือสถานที่"],
      "ตอบ I think it's Pim's. She was sitting there. เพราะ Whose ถามเจ้าของ",
      diff=2, sec=30, tags=["wh_type_mismatch"]),
    q(d("A: How much sugar would you like in your tea?", "B: ______"),
      "Just a little, please.",
      [("Two cups, please.", "ตอบจำนวนแก้วชา ไม่ใช่ปริมาณน้ำตาล"),
       ("Very much, thank you.", "ใช้ very much ในความหมายขอบคุณ ไม่ได้ตอบปริมาณ"),
       ("It costs 20 baht for a bag of sugar.", "ตีความ How much ว่าถามราคา")],
      [("How much + คำนามนับไม่ได้ = ปริมาณ", "ถามปริมาณน้ำตาล ไม่ใช่ราคา"),
       ("ตอบปริมาณ", "Just a little, please.")],
      ["How much ในประโยคนี้ถามราคาหรือปริมาณ ดูจากคำที่ตามมา",
       "sugar นับได้หรือนับไม่ได้",
       "หาตัวเลือกที่บอกปริมาณน้ำตาล"],
      "ตอบ Just a little, please. เพราะ How much sugar ถามปริมาณน้ำตาล ไม่ได้ถามราคา",
      diff=3, sec=35, tags=["wh_type_mismatch"]),
]
P += [
 N(d("A: How often does the shuttle run after six?","B: ______"),"Every thirty minutes until ten.",[("At the station entrance.","ตอบสถานที่แทนความถี่"),("About twenty passengers.","ตอบจำนวนคน"),("Because the buses are smaller.","ตอบเหตุผล")],"How often ต้องการความถี่","Every thirty minutes ตอบความถี่และเพิ่มช่วงเวลาที่เป็นประโยชน์",3,["wh_type_mismatch"]),
 N(d("A: Which route did Nina say avoids the roadworks?","B: ______"),"The riverside route, although it takes ten minutes longer.",[("At around half past eight.","ตอบเวลาแทนเส้นทาง"),("Because the main road is closed.","ตอบเหตุผล ไม่ระบุ route"),("Nina said it quite clearly.","บอกลักษณะการพูดแทนเนื้อหาคำตอบ")],"Which route ต้องการชื่อเส้นทาง ไม่ใช่เหตุผลหรือเวลา","ระบุเส้นทางและเงื่อนไขที่ไม่เปลี่ยนคำตอบ",5,["wh_type_mismatch"]),
]
save(tid, "TGAT1", "mcq4", P, lesson=L)

# ============================================================ yesno_and_tag
tid = B + "yesno_and_tag"
L = lesson(tid, "ตอบคำถาม Yes/No และคำถามท้ายประโยค",
    "ภาษาอังกฤษตอบ Yes/No ตามข้อเท็จจริง ไม่ใช่ตามว่าเห็นด้วยกับผู้ถามหรือไม่ — กลับกับภาษาไทย",
    objectives=["ตอบคำถามปฏิเสธ เช่น Don't you...? ได้ถูก", "ตอบคำถามท้ายประโยคได้ถูก", "ใช้กริยาช่วยในคำตอบสั้นให้ตรงกับคำถาม"],
    prereq=FOUND,
    blocks=[
        hook("\"You're not coming, are you?\" ถ้าคุณ **ไม่ไป** ต้องตอบ **\"No, I'm not.\"** "
             "คนไทยมักตอบ \"Yes\" เพราะในภาษาไทยเราตอบว่า \"ใช่ ไม่ไป\""),
        concept("กฎเดียวที่ต้องจำ",
                "**Yes = ข้อเท็จจริงเป็นบอกเล่า · No = ข้อเท็จจริงเป็นปฏิเสธ** ไม่สนว่าคำถามเป็นบอกเล่าหรือปฏิเสธ\n\n"
                "| คำถาม | ถ้าไป | ถ้าไม่ไป |\n|---|---|---|\n"
                "| Are you going? | Yes, I am. | No, I'm not. |\n"
                "| Aren't you going? | Yes, I am. | No, I'm not. |\n"
                "| You're going, aren't you? | Yes, I am. | No, I'm not. |\n"
                "| You aren't going, are you? | Yes, I am. | No, I'm not. |"),
        concept("คำตอบสั้นต้องใช้กริยาช่วยตัวเดียวกับคำถาม",
                "Did you...? → Yes, I did. · Have you...? → Yes, I have. · Can she...? → No, she can't.\n\n"
                "คำถามท้ายประโยค (tag question) ใช้กริยาช่วยของประโยคหลัก: She **has** finished, **hasn't** she?"),
        technique("แปลงเป็นประโยคข้อเท็จจริงก่อนตอบ",
                  "คำถามปฏิเสธ (Don't you / Isn't it) และ tag question ทุกข้อ",
                  "อย่าแปลเป็นไทยว่า 'ใช่หรือไม่ใช่' เพราะจะกลับด้าน",
                  "ถามตัวเองว่าข้อเท็จจริงคืออะไร เช่น \"ฉันไปไหม\" ถ้าไป → Yes + บอกเล่า ถ้าไม่ไป → No + ปฏิเสธ "
                  "Yes ต้องตามด้วยบอกเล่าเสมอ No ต้องตามด้วยปฏิเสธเสมอ",
                  tip="Yes + บอกเล่า · No + ปฏิเสธ · ห้ามผสม"),
        example("ตัวอย่างที่ 1",
                d("A: You didn't finish the project, did you?", "B: ______ I still need to write the conclusion."),
                [("ประโยคที่ตามมาบอกว่ายังต้องเขียนบทสรุป", "ข้อเท็จจริง: ยังไม่เสร็จ"),
                 ("ข้อเท็จจริงเป็นปฏิเสธ → No + ปฏิเสธ", "ใช้กริยาช่วย did → No, I didn't.")],
                "\"No, I didn't.\""),
        pitfall("ตอบแบบไทย",
                "A: Isn't it raining? (ฝนไม่ตกเหรอ) ฝนไม่ตกจริง → B: \"Yes, it isn't.\"",
                "Yes ต้องตามด้วยบอกเล่าเสมอ การผสม Yes กับ isn't ผิดไวยากรณ์",
                "\"No, it isn't.\"",
                "thai_style_yes_no"),
        pitfall("ใช้กริยาช่วยไม่ตรงกับคำถาม",
                "A: Have you eaten? → B: \"Yes, I did.\"",
                "คำถามใช้ have ต้องตอบด้วย have",
                "\"Yes, I have.\"",
                "auxiliary_mismatch"),
        summary("Yes = ข้อเท็จจริงบอกเล่า · No = ข้อเท็จจริงปฏิเสธ",
                "ไม่สนว่าคำถามเป็นบอกเล่าหรือปฏิเสธ",
                "Yes + บอกเล่า · No + ปฏิเสธ ห้ามผสม",
                "ใช้กริยาช่วยตัวเดียวกับคำถาม"),
        check(d("A: You don't eat meat, do you?", "B: ______ I'm vegetarian."),
              ["Yes, I do.", "Yes, I don't.", "No, I don't.", "No, I do."], 2,
              "B เป็นมังสวิรัติ ข้อเท็จจริงคือไม่กินเนื้อ → No, I don't."),
    ],
    patterns=["คำถามปฏิเสธ Don't you / Isn't it", "tag question ที่ต้องตอบตามข้อเท็จจริง", "คำตอบสั้นที่ใช้กริยาช่วยผิด"],
    sources=["ผังการสอบ TGAT1 จาก mytcas.com (พาร์ทการพูด ส่วนการถาม-ตอบ)", "ประโยคและบทสนทนาแต่งขึ้นใหม่เพื่อการฝึก"],
)
P = [
    q(d("A: Have you ever been to Phuket?", "B: ______ I went there last summer."),
      "Yes, I have.",
      [("Yes, I did.", "คำถามใช้ have ต้องตอบด้วย have ไม่ใช่ did"),
       ("No, I haven't.", "ขัดกับประโยคถัดไปที่บอกว่าไปมาแล้ว"),
       ("Yes, I went.", "ไม่ใช่รูปคำตอบสั้นมาตรฐาน")],
      [("ข้อเท็จจริง: เคยไปแล้ว", "Yes + บอกเล่า"),
       ("กริยาช่วยของคำถาม: have", "Yes, I have.")],
      ["B เคยไปภูเก็ตไหม ดูจากประโยคที่ตามมา",
       "คำถามใช้กริยาช่วยตัวไหน",
       "คำตอบสั้นต้องใช้กริยาช่วยตัวเดียวกับคำถาม"],
      "ตอบ Yes, I have. เพราะ B เคยไปแล้ว และคำถามใช้ have จึงต้องตอบด้วย have",
      diff=1, sec=25, tags=["auxiliary_mismatch"]),
    q(d("A: Aren't you hungry?", "B: ______ I just had a big lunch."),
      "No, I'm not.",
      [("Yes, I'm not.", "ผสม Yes กับประโยคปฏิเสธ ซึ่งผิดไวยากรณ์"),
       ("Yes, I am.", "ขัดกับเหตุผลว่าเพิ่งกินข้าวมาเยอะ"),
       ("No, I am.", "ผสม No กับประโยคบอกเล่า")],
      [("ข้อเท็จจริง: ไม่หิวเพราะเพิ่งกินมา", "ข้อเท็จจริงเป็นปฏิเสธ"),
       ("No + ปฏิเสธ", "No, I'm not.")],
      ["B หิวหรือไม่หิว ดูจากเหตุผลที่ตามมา",
       "ภาษาอังกฤษตอบ Yes/No ตามอะไร",
       "No ต้องตามด้วยประโยคแบบไหน"],
      "ตอบ No, I'm not. เพราะ B ไม่หิว ข้อเท็จจริงเป็นปฏิเสธ จึงใช้ No ตามด้วยปฏิเสธ",
      diff=2, sec=30, tags=["thai_style_yes_no"]),
    q(d("A: It's a beautiful day, isn't it?", "B: ______ Let's go for a walk."),
      "Yes, it is.",
      [("No, it isn't.", "ขัดกับการชวนออกไปเดินเล่น"),
       ("Yes, it isn't.", "ผสม Yes กับปฏิเสธ"),
       ("Yes, it does.", "ใช้กริยาช่วยผิด ประโยคหลักใช้ is")],
      [("ข้อเท็จจริง: อากาศดีจริง (B ชวนไปเดินเล่น)", "Yes + บอกเล่า"),
       ("กริยาช่วยของประโยคหลัก: is", "Yes, it is.")],
      ["B คิดว่าอากาศดีไหม ดูจากสิ่งที่ B ชวน",
       "ประโยคหลักใช้กริยาช่วยตัวไหน",
       "Yes ต้องตามด้วยประโยคแบบไหน"],
      "ตอบ Yes, it is. เพราะ B เห็นว่าอากาศดีจริงและชวนไปเดินเล่น ใช้กริยาช่วย is ตามประโยคหลัก",
      diff=1, sec=25, tags=["auxiliary_mismatch"]),
    q(d("A: You won't forget to bring the tickets, will you?", "B: ______ They're already in my bag."),
      "No, I won't.",
      [("Yes, I won't.", "ผสม Yes กับปฏิเสธ"),
       ("Yes, I will.", "แปลว่าจะลืม ขัดกับที่บอกว่าตั๋วอยู่ในกระเป๋าแล้ว"),
       ("No, I don't.", "ใช้กริยาช่วยผิด ต้องเป็น will")],
      [("ข้อเท็จจริง: จะไม่ลืม เพราะตั๋วอยู่ในกระเป๋าแล้ว", "ข้อเท็จจริงเป็นปฏิเสธ (won't forget)"),
       ("No + ปฏิเสธ ด้วยกริยาช่วย will", "No, I won't.")],
      ["คำถามคือ 'จะลืมไหม' B จะลืมหรือไม่ลืม",
       "ข้อเท็จจริง 'จะไม่ลืม' เป็นบอกเล่าหรือปฏิเสธเมื่อเทียบกับกริยา forget",
       "คำตอบสั้นต้องใช้กริยาช่วยตัวเดียวกับคำถาม"],
      "ตอบ No, I won't. เพราะ B จะไม่ลืม (ตั๋วอยู่ในกระเป๋าแล้ว) ข้อเท็จจริงเทียบกับ forget เป็นปฏิเสธ จึงใช้ No ตามด้วย won't",
      diff=4, sec=45, tags=["thai_style_yes_no"]),
    q(d("A: Didn't you see my message?", "B: ______ My phone was off all afternoon."),
      "No, I didn't. Sorry about that.",
      [("Yes, I didn't.", "ผสม Yes กับปฏิเสธ"),
       ("Yes, I did. My phone was off all afternoon, though.", "บอกว่าเห็นข้อความ ขัดกับเหตุผลว่าโทรศัพท์ปิด"),
       ("No, I haven't seen.", "ใช้กริยาช่วยไม่ตรงกับคำถามที่ใช้ did")],
      [("ข้อเท็จจริง: ไม่เห็นข้อความ เพราะโทรศัพท์ปิด", "No + ปฏิเสธ"),
       ("กริยาช่วยของคำถาม: did", "No, I didn't.")],
      ["B เห็นข้อความไหม ดูจากเหตุผลที่ตามมา",
       "คำถามปฏิเสธ Didn't you... ตอบตามข้อเท็จจริงหรือตามคำถาม",
       "กริยาช่วยในคำตอบต้องตรงกับคำถาม"],
      "ตอบ No, I didn't. Sorry about that. เพราะ B ไม่เห็นข้อความ จึงใช้ No ตามด้วยปฏิเสธด้วยกริยาช่วย did",
      diff=3, sec=35, tags=["thai_style_yes_no"]),
    q(d("A: She can speak Japanese, can't she?", "B: ______ She works as a Japanese interpreter."),
      "Yes, she can.",
      [("No, she can't.", "ขัดกับข้อมูลว่าเธอทำงานเป็นล่ามภาษาญี่ปุ่น"),
       ("Yes, she does.", "ใช้กริยาช่วยผิด ประโยคหลักใช้ can"),
       ("Yes, she can't.", "ผสม Yes กับปฏิเสธ")],
      [("ข้อเท็จจริง: พูดภาษาญี่ปุ่นได้ เพราะทำงานเป็นล่ามภาษาญี่ปุ่น", "Yes + บอกเล่า"),
       ("กริยาช่วยของประโยคหลัก: can", "Yes, she can.")],
      ["เธอพูดภาษาญี่ปุ่นได้ไหม ดูจากอาชีพที่ตามมา",
       "ประโยคหลักใช้กริยาช่วยตัวไหน",
       "Yes ต้องตามด้วยบอกเล่า"],
      "ตอบ Yes, she can. เพราะอาชีพล่ามภาษาญี่ปุ่นยืนยันว่าเธอพูดภาษาญี่ปุ่นได้ และประโยคหลักใช้ can",
      diff=2, sec=30, tags=["auxiliary_mismatch"]),
]
P += [
 N(d("A: Haven't you submitted the form yet?","B: ______"),"No, not yet. I'm waiting for one signature.",[("Yes, I haven't.","yes ขัดกับประโยคปฏิเสธที่ตามมา"),("No, I submitted it yesterday.","no ขัดกับข้อเท็จจริงที่บอกว่าส่งแล้ว"),("Yes, the form isn't a signature.","ไม่ตอบสถานะการส่งและความหมายผิด")],"คำถามปฏิเสธต้องตอบตามข้อเท็จจริงว่าส่งหรือยัง","No, not yet สอดคล้องกับการยังรอลายเซ็น",3,["thai_style_yes_no"]),
 N(d("A: You didn't copy the final file over the draft, did you?","B: ______"),"I'm afraid I did, but the backup should restore it.",[("No, I didn't not copy it.","ปฏิเสธซ้อนจนความหมายไม่ชัด"),("Yes, I didn't copy the draft.","yes ขัดกับ didn't และเปลี่ยนกรรม"),("The final file did, didn't it?","ให้ไฟล์เป็นผู้กระทำและเลียน tag โดยไม่ตอบ")],"tag question ใช้ยืนยันเหตุที่ผู้ถามกังวล","I did ยืนยันว่าเผลอเขียนทับจริง แล้วกล่าวถึงทางกู้คืน",5,["auxiliary_mismatch"]),
]
save(tid, "TGAT1", "mcq4", P, lesson=L)
